"""add chat message

Revision ID: ab0815361e14
Revises: f5607b1bc75f
Create Date: 2023-11-05 14:45:42.236761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab0815361e14'
down_revision = 'f5607b1bc75f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_message', sa.Column('question', sa.Text(), nullable=True))
    op.add_column('chat_message', sa.Column('answer', sa.Text(), nullable=True))
    op.add_column('chat_message', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('chat_message', sa.Column('chat_room_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chat_message', 'chat_room', ['chat_room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_message', type_='foreignkey')
    op.drop_column('chat_message', 'chat_room_id')
    op.drop_column('chat_message', 'created_at')
    op.drop_column('chat_message', 'answer')
    op.drop_column('chat_message', 'question')
    # ### end Alembic commands ###
