"""update chat message column

Revision ID: ac14e5491186
Revises: ab0815361e14
Create Date: 2023-11-05 17:03:21.663482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac14e5491186'
down_revision = 'ab0815361e14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_message', sa.Column('role', sa.Enum('system', 'user', 'assistant', name='roletype'), nullable=True))
    op.add_column('chat_message', sa.Column('content', sa.Text(), nullable=True))
    op.drop_column('chat_message', 'question')
    op.drop_column('chat_message', 'answer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_message', sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('chat_message', sa.Column('question', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('chat_message', 'content')
    op.drop_column('chat_message', 'role')
    # ### end Alembic commands ###
